setenv -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'
setenv -g PATH "/opt/homebrew/bin:/bin:/usr/bin"

set -g default-terminal "tmux-256color"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'maxpetretta/tmux-monokai-pro'

run ~/.config/tmux/plugins/tpm/tpm

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
