include kitty-monokaipro.conf

### appearance
confirm_os_window_close 0
macos_quit_when_last_window_closed yes
macos_show_window_title_in none
remember_window_size  yes
tab_bar_edge top
tab_bar_min_tabs 1
tab_title_template " {tab.active_wd.replace('/Users/ivanbanov', '~')} "
window_padding_width 10
tab_bar_margin_height 10 10

### keymap
# cursor
map cmd+left send_text all \x01
map cmd+right send_text all \x05
map alt+left send_text all \x1b[1;3D
map alt+right send_text all \x1b[1;3C

# window management
map cmd+w close_window
map cmd+enter new_window_with_cwd
map cmd+t new_tab_with_cwd

# window resize
map cmd+alt+right resize_window narrower
map cmd+alt+left resize_window wider
map cmd+alt+up resize_window taller
map cmd+alt+down resize_window shorter

# mouse click
mouse_map left click ungrabbed mouse_handle_click prompt
mouse_map cmd+left click ungrabbed mouse_handle_click link
